# Generated by Django 5.2.11 on 2026-03-03 08:23

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Содержание')),
                ('excerpt', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Мета-заголовок')),
                ('meta_description', models.TextField(blank=True, verbose_name='Мета-описание')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='Мета-ключевые слова')),
                ('show_in_header', models.BooleanField(default=False, verbose_name='Показывать в шапке')),
                ('show_in_footer', models.BooleanField(default=False, verbose_name='Показывать в подвале')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ['title'],
            },
        ),
    ]
