# Generated by Django 5.2 on 2025-12-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='meta_keywords',
            field=models.TextField(blank=True, verbose_name='Мета-ключевые слова'),
        ),
    ]
