# Generated by Django 5.2.13 on 2026-05-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['title'], 'verbose_name': 'страница', 'verbose_name_plural': 'Страницы'},
        ),
    ]
