# Generated by Django 5.2 on 2025-12-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_meta_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='show_in_header',
            field=models.BooleanField(default=False, verbose_name='Показывать в шапке'),
        ),
    ]
