# Generated by Django 5.2.11 on 2026-03-03 08:23

import django.db.models.deletion
import django_ckeditor_5.fields
import mybiz_core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', validators=[mybiz_core.validators.validate_image_extension, mybiz_core.validators.validate_image_size, mybiz_core.validators.validate_image_dimensions], verbose_name='Изображение')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Мета-заголовок')),
                ('meta_description', models.TextField(blank=True, verbose_name='Мета-описание')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='Мета-ключевые слова')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mybiz_core.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена со скидкой')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Бренд')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', validators=[mybiz_core.validators.validate_image_extension, mybiz_core.validators.validate_image_size, mybiz_core.validators.validate_image_dimensions], verbose_name='Изображение')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Рейтинг')),
                ('review_count', models.IntegerField(default=0, verbose_name='Количество отзывов')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('stock', models.IntegerField(default=0, verbose_name='Остаток на складе')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемый')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='mybiz_core.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
    ]
