# Generated by Django 5.2.9 on 2026-02-10 14:00

import django_ckeditor_5.fields
import mybiz_core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybiz_core', '0002_alter_category_options_remove_category_order_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='mybiz_core__slug_7d0c20_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='mybiz_core__is_acti_098c0c_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='mybiz_core__parent__129321_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='mybiz_core__slug_f4fbe9_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='mybiz_core__categor_6eba76_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='mybiz_core__is_acti_579aa0_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='mybiz_core__name_d80538_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='mybiz_core__brand_a6289b_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='mybiz_core__price_27cffc_idx',
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Мета-описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords',
            field=models.TextField(blank=True, verbose_name='Мета-ключевые слова'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Мета-заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Новинка'),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='product',
            name='review_count',
            field=models.IntegerField(default=0, verbose_name='Количество отзывов'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default='DEFAULT_SKU_123', max_length=50, unique=True, verbose_name='Артикул'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена со скидкой'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='products/', validators=[mybiz_core.validators.validate_image_extension, mybiz_core.validators.validate_image_size, mybiz_core.validators.validate_image_dimensions], verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Остаток на складе'),
        ),
    ]
