# Generated by Django 5.2.13 on 2026-05-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybiz_core', '0002_alter_product_created_at_alter_product_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
