# Generated by Django 5.2 on 2025-12-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybiz_core', '0003_product_product_category_active_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='product_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'price'], name='product_active_price_idx'),
        ),
    ]
