# Generated by Django 5.2.11 on 2026-03-03 08:23

import django.db.models.deletion
import django_ckeditor_5.fields
import mybiz_core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mybiz_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Подписчик',
                'verbose_name_plural': 'Подписчики',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('button_text', models.CharField(blank=True, max_length=50, verbose_name='Текст кнопки')),
                ('button_url', models.CharField(blank=True, max_length=200, verbose_name='URL кнопки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', models.ImageField(upload_to='promotions/', validators=[mybiz_core.validators.validate_image_extension, mybiz_core.validators.validate_image_size, mybiz_core.validators.validate_image_dimensions], verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Промо-акция',
                'verbose_name_plural': 'Промо-акции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_scheme', models.CharField(choices=[('wood', '🌳 Дерево - Натуральные экологичные тона'), ('coffee', '☕ Кофе - Теплые уютные оттенки'), ('flower', '🌺 Цветок - Яркая сбалансированная палитра'), ('vintage', '📻 Винтаж - Классические приглушенные тона'), ('pastel', '🎨 Пастель - Мягкие нежные цвета'), ('custom', '✏️ Пользовательская тема - Настройте цвета вручную')], default='wood', max_length=20, verbose_name='Цветовая схема сайта')),
                ('site_name', models.CharField(default='MyBiz', max_length=100, verbose_name='Название сайта')),
                ('site_tagline', models.CharField(blank=True, max_length=200, verbose_name='Слоган сайта')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/', validators=[mybiz_core.validators.validate_image_extension, mybiz_core.validators.validate_image_size], verbose_name='Фавикон')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', validators=[mybiz_core.validators.validate_image_extension, mybiz_core.validators.validate_image_size, mybiz_core.validators.validate_image_dimensions], verbose_name='Логотип')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/', validators=[mybiz_core.validators.validate_image_extension, mybiz_core.validators.validate_image_size, mybiz_core.validators.validate_image_dimensions], verbose_name='Главное изображение')),
                ('primary_color', models.CharField(default='#3b82f6', help_text='Основной цвет бренда', max_length=7, verbose_name='Основной цвет (Primary)')),
                ('secondary_color', models.CharField(default='#8b5cf6', help_text='Дополнительный цвет', max_length=7, verbose_name='Вторичный цвет (Secondary)')),
                ('accent_color', models.CharField(default='#10b981', help_text='Цвет для кнопок и важных элементов', max_length=7, verbose_name='Акцентный цвет (Accent)')),
                ('text_color', models.CharField(default='#1f2937', help_text='Основной цвет текста', max_length=7, verbose_name='Цвет текста')),
                ('background_color', models.CharField(default='#f9fafb', help_text='Фоновый цвет сайта', max_length=7, verbose_name='Цвет фона')),
                ('header_bg_color', models.CharField(default='#ffffff', help_text='Фон верхней части сайта', max_length=7, verbose_name='Фон шапки')),
                ('footer_bg_color', models.CharField(default='#111827', help_text='Фон нижней части сайта', max_length=7, verbose_name='Фон подвала')),
                ('hero_bg_color', models.CharField(default='#eff6ff', help_text='Фоновый цвет главного баннера на главной странице', max_length=7, verbose_name='Фон герой-секции')),
                ('hero_heading_prefix', models.CharField(default='Добро пожаловать в', help_text='Текст перед названием сайта в главном баннере', max_length=100, verbose_name='Префикс заголовка (hero)')),
                ('welcome_text', models.TextField(blank=True, default='Современная витрина качественных товаров. Мы тщательно отбираем каждый продукт, чтобы предложить вам лучшее сочетание цены и качества.', help_text='Основной текст под заголовком на главной', verbose_name='Приветственный текст')),
                ('advantages_heading', models.CharField(default='Почему выбирают нас', max_length=200, verbose_name='Заголовок блока преимуществ')),
                ('advantages_subheading', models.TextField(blank=True, default='Мы заботимся о каждом клиенте и гарантируем качество', verbose_name='Подзаголовок блока преимуществ')),
                ('show_statistics', models.BooleanField(default=True, verbose_name='Показывать блок статистики')),
                ('show_advantages', models.BooleanField(default=True, verbose_name='Показывать блок преимуществ')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Контактный email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Контактный телефон')),
                ('contact_address', models.TextField(blank=True, verbose_name='Контактный адрес')),
                ('working_hours', models.CharField(blank=True, max_length=100, verbose_name='Время работы')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('telegram_visible', models.BooleanField(default=True, verbose_name='Показывать Telegram')),
                ('vk_url', models.URLField(blank=True, verbose_name='VK')),
                ('vk_visible', models.BooleanField(default=True, verbose_name='Показывать VK')),
                ('max_url', models.URLField(blank=True, verbose_name='MAX')),
                ('max_visible', models.BooleanField(default=True, verbose_name='Показывать MAX')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('instagram_visible', models.BooleanField(default=True, verbose_name='Показывать Instagram')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Мета-заголовок')),
                ('meta_description', models.TextField(blank=True, verbose_name='Мета-описание')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='Мета-ключевые слова')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(choices=[('check', '✓ Галочка (качество)'), ('truck', '🚚 Грузовик (доставка)'), ('lock', '🔒 Замок (безопасность)'), ('headset', '🎧 Гарнитура (поддержка)'), ('star', '⭐ Звезда (популярность)'), ('heart', '❤️ Сердце (любовь клиентов)'), ('clock', '🕒 Часы (быстрота)'), ('shield', '🛡️ Щит (гарантия)'), ('credit-card', '💳 Кредитка (оплата)'), ('gift', '🎁 Подарок (акции)'), ('phone', '📱 Телефон (связь)'), ('map-pin', '📍 Метка (адрес)'), ('users', '👥 Люди (команда)'), ('award', '🏆 Награда (достижения)'), ('thumbs-up', '👍 Палец вверх (одобрение)'), ('refresh', '🔄 Обновление (возврат)'), ('discount', '🏷️ Скидка (цена)'), ('package', '📦 Посылка (упаковка)'), ('coffee', '☕ Кофе (сервис)'), ('wifi', '📶 Wi-Fi (технологии)')], default='check', max_length=20, verbose_name='Иконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('site_settings', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='content.sitesettings', verbose_name='Настройки сайта')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: «Товаров в каталоге», «Поддержка клиентов»', max_length=100, verbose_name='Заголовок')),
                ('value_number', models.PositiveIntegerField(blank=True, help_text='Заполните, если нужна цифра с анимацией (например, 200). Оставьте пустым, если используете текст ниже.', null=True, verbose_name='Числовое значение')),
                ('value_text', models.CharField(blank=True, help_text='Заполните, если нужен текст (например, «24/7»). Оставьте пустым, если используете число выше.', max_length=50, verbose_name='Текстовое значение')),
                ('suffix', models.CharField(blank=True, help_text='Добавьте символ после значения: %, /7, ₽ и т.п.', max_length=10, verbose_name='Суффикс')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше будет блок', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, help_text='Снимите галочку, чтобы временно скрыть показатель', verbose_name='Активно')),
                ('site_settings', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='content.sitesettings', verbose_name='Настройки сайта')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистики',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StockNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_notified', models.BooleanField(default=False, verbose_name='Уведомление отправлено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybiz_core.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Запрос о поступлении',
                'verbose_name_plural': 'Запросы о поступлении',
                'unique_together': {('product', 'email')},
            },
        ),
    ]
