# Generated by Django 5.2.11 on 2026-03-04 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='site_settings',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='advantages_heading',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='advantages_subheading',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='show_advantages',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='show_statistics',
        ),
        migrations.DeleteModel(
            name='Advantage',
        ),
        migrations.DeleteModel(
            name='Statistic',
        ),
    ]
