# Generated by Django 5.2 on 2025-12-16 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(default='#10b981', help_text='HEX-код акцентного цвета для кнопок (например, #10b981)', max_length=7, validators=[django.core.validators.RegexValidator('^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$', 'Введите корректный HEX-код цвета')], verbose_name='Акцентный цвет'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='background_color',
            field=models.CharField(default='#f9fafb', help_text='HEX-код фона сайта (например, #f9fafb)', max_length=7, validators=[django.core.validators.RegexValidator('^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$', 'Введите корректный HEX-код цвета')], verbose_name='Цвет фона'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_bg_color',
            field=models.CharField(default='#111827', help_text='HEX-код фона подвала сайта (например, #111827)', max_length=7, validators=[django.core.validators.RegexValidator('^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$', 'Введите корректный HEX-код цвета')], verbose_name='Фон подвала'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_bg_color',
            field=models.CharField(default='#ffffff', help_text='HEX-код фона шапки сайта (например, #ffffff)', max_length=7, validators=[django.core.validators.RegexValidator('^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$', 'Введите корректный HEX-код цвета')], verbose_name='Фон шапки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#3b82f6', help_text='HEX-код основного цвета (например, #3b82f6)', max_length=7, validators=[django.core.validators.RegexValidator('^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$', 'Введите корректный HEX-код цвета')], verbose_name='Основной цвет'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='secondary_color',
            field=models.CharField(default='#8b5cf6', help_text='HEX-код вторичного цвета (например, #8b5cf6)', max_length=7, validators=[django.core.validators.RegexValidator('^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$', 'Введите корректный HEX-код цвета')], verbose_name='Вторичный цвет'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='text_color',
            field=models.CharField(default='#1f2937', help_text='HEX-код основного цвета текста (например, #1f2937)', max_length=7, validators=[django.core.validators.RegexValidator('^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$', 'Введите корректный HEX-код цвета')], verbose_name='Цвет текста'),
        ),
    ]
