# Generated by Django 5.2.11 on 2026-03-05 06:54

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_statistic_site_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='featured_products_subtitle',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='Самые востребованные товары среди наших покупателей', verbose_name='Подзаголовок блока популярных товаров'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='featured_products_title',
            field=models.CharField(default='Популярные товары', max_length=200, verbose_name='Заголовок блока популярных товаров'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='Лучшие товары по доступным ценам', help_text='Отображается под названием сайта на главной. Если пусто – используется site_tagline', verbose_name='Подзаголовок Hero'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='promotions_subtitle',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='Не упустите возможность приобрести товары по выгодным ценам', verbose_name='Подзаголовок блока акций'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='promotions_title',
            field=models.CharField(default='Специальные предложения', max_length=200, verbose_name='Заголовок блока акций'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='welcome_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='Современная витрина качественных товаров. Мы тщательно отбираем каждый продукт, чтобы предложить вам лучшее сочетание цены и качества.', help_text='Основной текст под заголовком на главной (поддерживает форматирование)', verbose_name='Приветственный текст'),
        ),
    ]
