# Generated by Django 5.2 on 2025-12-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_promotion_image_alter_sitesettings_favicon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='twitter_url',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='max_url',
            field=models.URLField(blank=True, verbose_name='MAX'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_url',
            field=models.URLField(blank=True, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vk_url',
            field=models.URLField(blank=True, verbose_name='VK'),
        ),
    ]
