# Generated by Django 5.2.11 on 2026-03-05 07:16

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_sitesettings_featured_products_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='featured_products_title',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='Популярные товары', help_text='Заголовок секции популярных товаров (поддерживает простое форматирование)', verbose_name='Заголовок блока популярных товаров'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='promotions_title',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='Специальные предложения', help_text='Заголовок секции акций (поддерживает простое форматирование)', verbose_name='Заголовок блока акций'),
        ),
    ]
