# Generated by Django 5.2 on 2025-12-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_sitesettings_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_visible',
            field=models.BooleanField(default=True, verbose_name='Показывать Instagram'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='max_visible',
            field=models.BooleanField(default=True, verbose_name='Показывать MAX'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_visible',
            field=models.BooleanField(default=True, verbose_name='Показывать Telegram'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vk_visible',
            field=models.BooleanField(default=True, verbose_name='Показывать VK'),
        ),
    ]
