# Generated by Django 5.2.11 on 2026-03-05 07:28

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_sitesettings_featured_products_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='featured_products_title',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='Популярные товары', help_text='Заголовок секции популярных товаров', verbose_name='Заголовок блока популярных товаров'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_heading_prefix',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='Добро пожаловать в', help_text='Текст перед названием сайта в главном баннере (может содержать простое форматирование)', max_length=100, verbose_name='Префикс заголовка (hero)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='promotions_title',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='Специальные предложения', help_text='Заголовок секции акций', verbose_name='Заголовок блока акций'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=django_ckeditor_5.fields.CKEditor5Field(default='MyBiz', help_text='Название сайта (может содержать простое форматирование)', max_length=200, verbose_name='Название сайта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_tagline',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='Лучшие товары по доступным ценам', help_text='Краткий слоган (может содержать простое форматирование)', max_length=200, verbose_name='Слоган сайта'),
        ),
    ]
