# Generated by Django 5.2.11 on 2026-03-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_sitesettings_featured_products_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='border_color',
            field=models.CharField(default='#e5e7eb', help_text='Цвет границ элементов', max_length=7, verbose_name='Цвет границ'),
        ),
    ]
