# Generated by Django 5.2.11 on 2026-04-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_sitesettings_border_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='featured_products_subtitle',
            field=models.CharField(blank=True, default='Самые востребованные товары среди наших покупателей', max_length=300, verbose_name='Подзаголовок блока популярных товаров'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='featured_products_title',
            field=models.CharField(blank=True, default='Популярные товары', help_text='Заголовок секции популярных товаров', max_length=200, verbose_name='Заголовок блока популярных товаров'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_heading_prefix',
            field=models.CharField(blank=True, default='Добро пожаловать в', help_text='Текст перед названием сайта в главном баннере', max_length=100, verbose_name='Префикс заголовка (hero)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.CharField(blank=True, default='Лучшие товары по доступным ценам', help_text='Отображается под названием сайта на главной. Если пусто – используется site_tagline', max_length=200, verbose_name='Подзаголовок Hero'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='promotions_subtitle',
            field=models.CharField(blank=True, default='Не упустите возможность приобрести товары по выгодным ценам', max_length=300, verbose_name='Подзаголовок блока акций'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='promotions_title',
            field=models.CharField(blank=True, default='Специальные предложения', help_text='Заголовок секции акций', max_length=200, verbose_name='Заголовок блока акций'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='MyBiz', help_text='Название сайта', max_length=200, verbose_name='Название сайта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_tagline',
            field=models.CharField(blank=True, default='Лучшие товары по доступным ценам', help_text='Краткий слоган', max_length=200, verbose_name='Слоган сайта'),
        ),
    ]
