# Generated by Django 5.2.11 on 2026-04-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_sitesettings_featured_products_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Процент (%)'), ('fixed', 'Фиксированная сумма (₽)')], default='percent', max_length=10, verbose_name='Тип скидки'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Значение скидки'),
        ),
    ]
