# Generated by Django 5.2.11 on 2026-04-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_promotion_discount_type_promotion_discount_value'),
        ('mybiz_core', '0002_alter_product_created_at_alter_product_is_active_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stocknotification',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_value',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=5, verbose_name='Значение скидки'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['is_active'], name='content_pro_is_acti_edf5cc_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['start_date'], name='content_pro_start_d_081bc8_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['end_date'], name='content_pro_end_dat_da0016_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocknotification',
            constraint=models.UniqueConstraint(fields=('product', 'email'), name='unique_product_email'),
        ),
    ]
