# Generated by Django 5.2.11 on 2026-04-25 08:29

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_stocknotification_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='header_font_family',
            field=models.CharField(blank=True, default='Poppins, sans-serif', help_text='CSS font-family для хедера', max_length=100, verbose_name='Шрифт шапки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_font_size',
            field=models.PositiveIntegerField(default=16, help_text='Базовый размер шрифта в пикселях', verbose_name='Размер шрифта шапки (px)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_text_color',
            field=models.CharField(default='#1f2937', max_length=7, verbose_name='Цвет текста в шапке'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(default='#10b981', max_length=7, verbose_name='Акцентный цвет (Accent)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='background_color',
            field=models.CharField(default='#f9fafb', max_length=7, verbose_name='Цвет фона'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='border_color',
            field=models.CharField(default='#e5e7eb', max_length=7, verbose_name='Цвет границ'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='featured_products_subtitle',
            field=models.CharField(blank=True, default='Самые востребованные товары...', max_length=300, verbose_name='Подзаголовок блока популярных товаров'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='featured_products_title',
            field=models.CharField(blank=True, default='Популярные товары', max_length=200, verbose_name='Заголовок блока популярных товаров'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_bg_color',
            field=models.CharField(default='#111827', max_length=7, verbose_name='Фон подвала'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='header_bg_color',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='Фон шапки'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_bg_color',
            field=models.CharField(default='#eff6ff', max_length=7, verbose_name='Фон герой-секции'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.CharField(blank=True, default='Лучшие товары по доступным ценам', max_length=200, verbose_name='Подзаголовок Hero'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#3b82f6', max_length=7, verbose_name='Основной цвет (Primary)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='promotions_subtitle',
            field=models.CharField(blank=True, default='Не упустите возможность...', max_length=300, verbose_name='Подзаголовок блока акций'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='promotions_title',
            field=models.CharField(blank=True, default='Специальные предложения', max_length=200, verbose_name='Заголовок блока акций'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='secondary_color',
            field=models.CharField(default='#8b5cf6', max_length=7, verbose_name='Вторичный цвет (Secondary)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='text_color',
            field=models.CharField(default='#1f2937', max_length=7, verbose_name='Цвет текста'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='welcome_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='Современная витрина качественных товаров...', verbose_name='Приветственный текст'),
        ),
    ]
