# Generated by Django 5.2.11 on 2026-04-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_sitesettings_header_font_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='header_font_choice',
            field=models.CharField(choices=[('poppins', 'Poppins, sans-serif'), ('inter', 'Inter, sans-serif'), ('roboto', 'Roboto, sans-serif'), ('georgia', 'Georgia, serif'), ('courier', 'Courier New, monospace'), ('custom', 'Другой шрифт...')], default='poppins', max_length=50, verbose_name='Шрифт шапки'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='header_font_family',
            field=models.CharField(blank=True, default='', help_text='Введите название шрифта, если выбран «Другой шрифт…»', max_length=100, verbose_name='Свой шрифт'),
        ),
    ]
