# Generated by Django 5.2.11 on 2026-04-25 10:28

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_sitesettings_header_font_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='featured_products_title',
            field=models.CharField(blank=True, default='Популярные товары', help_text='Заголовок секции популярных товаров', max_length=200, verbose_name='Заголовок блока популярных товаров'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='promotions_title',
            field=models.CharField(blank=True, default='Специальные предложения', help_text='Заголовок секции акций', max_length=200, verbose_name='Заголовок блока акций'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=django_ckeditor_5.fields.CKEditor5Field(default='MyBiz', help_text='Название сайта (можно использовать форматирование)', max_length=200, verbose_name='Название сайта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_tagline',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='Лучшие товары по доступным ценам', help_text='Краткий слоган (поддерживает простое форматирование)', max_length=200, verbose_name='Слоган сайта'),
        ),
    ]
