# Generated by Django 5.2.11 on 2026-04-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_alter_sitesettings_featured_products_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='featured_products_title',
            field=models.CharField(blank=True, default='Популярные товары', max_length=200, verbose_name='Заголовок блока популярных товаров'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='promotions_title',
            field=models.CharField(blank=True, default='Специальные предложения', max_length=200, verbose_name='Заголовок блока акций'),
        ),
    ]
