# Generated by Django 5.2.11 on 2026-04-25 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_alter_sitesettings_featured_products_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='header_font_choice',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='header_font_family',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='header_font_size',
        ),
    ]
