# Generated by Django 5.2.11 on 2026-04-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_remove_header_font_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text_color',
            field=models.CharField(default='#f9fafb', max_length=7, verbose_name='Цвет текста в подвале'),
        ),
    ]
