# Generated by Django 6.0.4 on 2026-05-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_add_footer_text_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(default='#10b981', max_length=7, verbose_name='Акцентный цвет'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#3b82f6', max_length=7, verbose_name='Основной цвет'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='secondary_color',
            field=models.CharField(default='#8b5cf6', max_length=7, verbose_name='Вторичный цвет'),
        ),
    ]
