# Generated by Django 5.2.13 on 2026-05-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_remove_english_from_color_verbose_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettersubscriber',
            options={'ordering': ['-created_at'], 'verbose_name': 'подписчик', 'verbose_name_plural': 'Подписчики'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['-created_at'], 'verbose_name': 'промо-акция', 'verbose_name_plural': 'Промо-акции'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'настройка сайта', 'verbose_name_plural': 'Настройки сайта'},
        ),
        migrations.AlterModelOptions(
            name='stocknotification',
            options={'verbose_name': 'запрос о поступлении', 'verbose_name_plural': 'Запросы о поступлении'},
        ),
    ]
