# Generated by Django 5.2.13 on 2026-05-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_alter_newslettersubscriber_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_bg_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_text_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='header_bg_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='header_text_color',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_footer_bg_color',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='Фон шапки и подвала'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_footer_text_color',
            field=models.CharField(default='#1f2937', max_length=7, verbose_name='Цвет текста шапки и подвала'),
        ),
    ]
