# Generated by Django 5.2.13 on 2026-05-08 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_update_header_footer_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_bg_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_heading_prefix',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_subtitle',
        ),
    ]
